---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: gitrevision
      default: main
      description: The git revsion to checkout and build, a branch or sha, default to main
    - name: gitrepositoryurl
      description: The git repository url
    - name: registryurl
      description: The registry url built images target
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        generateName: github-run-
      spec:
        serviceAccountName: docker-creds
        taskRef:
          name: buildpacks-v3
        outputs:
         resources:
         - name: image
           resourceSpec:
             type: image
             params:
             - name: url
               value: $(params.registryurl) 
        inputs:
          resources:
            - name: source
              resourceSpec:
                type: git
                params:
                  - name: revision
                    value: $(params.gitrevision)
                  - name: url
                    value: $(params.gitrepositoryurl)
